config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :memories do
    resources :comments, only: [:create, :update, :destroy]
  end
  root 'static_pages#home'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :memory

  validates :body, presence: true

  scope :pending_comment, -> { where approved: false }
  scope :approved_comment, -> { where approved: true }
end

app/models/memory.rb
class Memory < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings

  validates :name, presence: true
  validates :description, presence: true

  scope :related_tags, -> (u) { joins(:tags).where(tags: { id: u.tags.pluck(&:id).flatten })}
  scope :related_users, -> (u) { joins(:user).where.not(users: { id: u })}
  scope :recent_memories, -> { order(:created_at => :desc) }

    def pending_comments?
      self.comments.pending_comment.count > 0
    end

    # Tag Related Methods

    def self.tagged_with(name)
      Tag.find_by_name!(name).memories
    end

    def tag_list
      tags.map(&:name).join(", ")
    end

    def tag_list=(names)
      self.tags = names.split(",").map do |n|
        Tag.where(name: n.strip).first_or_create!
      end
    end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :memories, through: :taggings

  validates :name, presence: true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :memory
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :memories
  has_many :tags, through: :memories

  validates :email, length: { maximum: 255 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == 'admin'
  end

  def registered?
    role == 'registered'
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = "#{auth.info.nickname}@twitter.com"
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected
    def after_sign_in_path_for(_resource)
      memories_path
    end
  private

  def user_not_authorized
    redirect_to(request.referrer || root_path)
    flash[:alert] = "You are not authorized to perfrom this action."
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  after_action :verify_authorized, unless: :devise_controller?

  def create
    @memory = Memory.find(params[:memory_id])
    @comment = @memory.comments.build(comment_params)
    @comment.approved = true if current_user == @memory.user
    authorize @comment
    if @comment.save
      redirect_to memory_path(@memory), notice: 'Comment Sent, Awaiting Approval.'
    else
      redirect_to @memory, alert: 'Unable to send the comment', notice: 'Comment can\'t be blank'
    end
  end

  def update
    @memory = Memory.find(params[:memory_id])
    @comment = Comment.find(params[:id])
    authorize @comment
    if @comment.update(comment_params)
      redirect_to memory_path(@memory), notice: 'Comment Approved.'
    else
      redirect_to @memory, alert: 'Unable to approve comment', notice: 'Unable to approve comment'
    end
  end

  def destroy
    @memory = Memory.find(params[:memory_id])
    @comment = Comment.find(params[:id])
    authorize @comment
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @memory, notice: 'Comment Declined.' }
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:body, :memory_id, :approved)
    end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :set_memory, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized, unless: :devise_controller?

  def index
    @memories = Memory.all
    authorize @memories
  end

  def new
    @memory = current_user.memories.build
    authorize @memory
  end

  def show
    authorize @memory
  end

  def edit
    authorize @memory
  end

  def create
    @memory = current_user.memories.build(memory_params)
    authorize @memory
    respond_to do |format|
      if @memory.save
        format.html { redirect_to @memory, notice: "Memory was successfully created."}
      else
        format.html { render :new }
      end
    end
  end

  def update
    authorize @memory
    respond_to do |format|
      if @memory.update(memory_params)
        format.html { redirect_to @memory, notice: "Memory was successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    authorize @memory
    @memory.destroy
  end

  private

  def set_memory
    @memory = Memory.find(params[:id])
  end

    def memory_params
      params.require(:memory).permit(:name, :description, :tag_list)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = 'Signed in!'
      sign_in_and_redirect user
    else
      session['devise.user_attributes'] = user.attributes
      redirect_to new_user_registration_url
    end
  end

  alias_method :twitter, :all
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      :success => 'alert-success',
      :error => 'alert-danger',
      :alert => 'alert-warning',
      :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
  def pending? user, memory
    current_user == memory.user && memory.pending_comments?
  end

  def related_memories_to_user user
    Memory.related_tags(user).related_users(user).first(6)
  end

  def most_recent_memories user
    Memory.recent_memories.related_users(user).first(6)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_form.html.erb
<% if pending? current_user, @memory %>
<%= render partial: 'comments/pending', memory: @memory %>
<% end %>

<% if policy(Comment).new? %>
  <h2>Add a comment:</h2>
  <%= form_for([@memory, @memory.comments.build]) do |f| %>
    <p>
      <%= f.label :body %> <br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
<% end %>

<h2> Comments</h2>
<% @memory.comments.approved_comment.each do |comment| %>
  <p>
    <strong>Comment</strong>
    <%= comment.body %>
    <%= comment.approved %>
  </p>
<% end %>

app/views/comments/_pending.html.erb
<% @memory.comments.pending_comment.each do |pending| %>
  <p>
  <%= pending.body %>
  <%= form_for([pending.memory, pending]) do |f| %>
    <%= f.submit 'Approve', class: "button success round" %>
    <%= f.hidden_field :approved, value: true %>
  <% end %>
  <%= button_to "Decline", ([pending.memory, pending]), method: :delete, data: {confirm: 'Are you sure?' } %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thundrs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'static_pages/header'  %>
<% flash.each do |type, message| %>
  <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>
<%= yield %>
</body>
</html>

app/views/memories/_form.html.erb
<%= form_for @memory do |f| %>
  <% if @memory.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@memory.errors.count, "error") %> prohibited
        this memory from being saved:
      </h2>
      <ul>
        <% @memory.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :tag_list, 'Tag List (Separate Tags with Commas)' %><br>
    <%= f.text_area :tag_list%>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/memories/edit.html.erb
<h1>Editing Memory</h1>

<%= render 'form' %>

<%= link_to 'Show', @memory %> |
<%= link_to 'Back', @memories_path %>

app/views/memories/index.html.erb
<h1>Related Memories</h1>
<div class="small-12 medium-12 large-12 columns panel radius">
  <div class="related-memories">
    <% @related_memories = related_memories_to_user current_user %>
    <% if @related_memories.size > 0 %>
      <% @related_memories.each do |memory| %>
        <%= memory.name %>
        <%= memory.tag_list %>
      <% end %>
    <% else %>
      <strong> No Related Memories
    <% end %>
  </div>
</div>

<h1>Recent Memories</h1>
<div class="small-12 medium-12 large-12 columns panel panel-primary radius">
  <div class="recent-memories">
    <% @recent_memories = most_recent_memories current_user %>
    <% if @recent_memories.size > 0 %>
      <% @recent_memories.each do |memory| %>
        <%= memory.name %>
        <%= memory.tag_list %>
      <% end %>
    <% else %>
      <strong> No Recent Memories
    <% end %>
  </div>
</div>

<h1>Memories</h1>
<table id="list">
  <thead>
    <tr>
      <th>Memory</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @memories.each do |memory| %>
    <tr id="<%= dom_id(memory) %>">
      <td class="name"><%= memory.name %></td>
      <td class="description"><%= memory.description %></td>
      <td><%= link_to 'Show', memory_path(memory) %></td>

      <% if policy(memory).edit? %>
        <td><%= link_to 'Edit', edit_memory_path(memory) %></td>
      <% end %>
      <% if policy(memory).destroy? %>
        <td><%= link_to 'Destroy', memory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
 <% if user_signed_in? %>
<%= link_to 'New Memory', new_memory_path, id: "new_link" %>
<% end %>

app/views/memories/new.html.erb
<h1> Add A Memory </h1>
<%= render 'form' %>
<%= link_to 'Back', memories_path %>

app/views/memories/show.html.erb
<p>
  <em>Name</em>
  <%= @memory.name %>
</p>

<p>
  <em>Description</em>
  <%= @memory.description %>
</p>

<p>
  <em>Tags:</em>
  <%= @memory.tag_list %>
</p>

<%= render 'comments/form' %>

app/views/static_pages/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
      <% if user_signed_in? %>
        <button type="button" class="btn btn-defualt navbar-btn pull-right">
          <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
        </button>
      <% else %>
        <button type="button" class="btn btn-defualt navbar-btn pull-right">
          <%= link_to 'Sign up', new_user_registration_path %>
        </button>
        <button type="button" class="btn btn-default navbar-btn pull-right">
          <%= link_to 'Login', new_user_session_path %>
        </button>
        <button type="button" class="btn btn-default navbar-btn pull-right">
          <a href="/users/auth/twitter">Sign in with Twitter</a>
        </button>
      <% end %>
  <div>
</nav>

app/views/static_pages/home.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-sm-6 col-md-8'>
      <div class="panel panel-default">
        <div class="panel-body">
          <h1>Welcome</h1>
          <p>Future Home of Thundrs</p>
        </div>
      </div>
    </div>
    <div class='col-sm-6 col-md-4 .visible-sm-block, hidden-xs'>
      <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae, ut, nostrum. Ducimus voluptatem tenetur officia dolores dignissimos non repellat perspiciatis tempore obcaecati facere animi pariatur earum placeat, fugiat, quam provident.</div>
      <div>Perferendis odit inventore quasi ducimus sint repellendus, sunt fugit doloremque aliquam, ipsam nostrum reiciendis quaerat eligendi! Atque laudantium tempora voluptatibus magni architecto vitae repellendus, sit voluptate! Eaque, impedit provident magni!</div>
      <div>Temporibus quo architecto vitae accusamus mollitia sapiente suscipit molestias, eveniet, sequi. Et quibusdam quod placeat maxime illo autem consectetur rerum molestiae eos amet, ipsum omnis, libero, at voluptas obcaecati expedita!</div>
      <div>Voluptatem asperiores placeat cum explicabo repellendus magnam deleniti dolorum minus! Quaerat et ab totam consequatur. Ea accusantium saepe hic praesentium error. Asperiores, repellat vel distinctio assumenda provident possimus deserunt. Suscipit!</div>
      <div>Corrupti, molestiae sequi neque id. Illum quibusdam enim laborum cumque non iusto nulla nisi facilis, ab officia numquam illo veritatis molestias! Laudantium dolore consectetur praesentium nisi eveniet fugiat ipsa culpa.</div>
    </div>
  </div>
</div>